packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  happy-dom: ^20.9.0
  "@babel/parser": ^7.29.3
  "@babel/traverse": ^7.29.0
  "@babel/generator": ^7.29.1
  "@babel/types": ^7.29.0
  "@babel/plugin-syntax-jsx": ^7.28.6
  "@types/babel__traverse": ^7.28.0
  "@types/babel__generator": ^7.27.0
  "@types/babel__core": ^7.20.5
  tailwindcss: ^4.3.0
  "@tailwindcss/vite": ^4.3.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  esbuild: true
